// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: nebula_agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_nebula_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{0}
}

type GetNodeInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage         float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsedMb     int64                  `protobuf:"varint,2,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	DiskUsedGb       int64                  `protobuf:"varint,3,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"`
	LoadAverage      float64                `protobuf:"fixed64,4,opt,name=load_average,json=loadAverage,proto3" json:"load_average,omitempty"`
	RunningInstances int32                  `protobuf:"varint,5,opt,name=running_instances,json=runningInstances,proto3" json:"running_instances,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_nebula_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetNodeInfoResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetNodeInfoResponse) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *GetNodeInfoResponse) GetDiskUsedGb() int64 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

func (x *GetNodeInfoResponse) GetLoadAverage() float64 {
	if x != nil {
		return x.LoadAverage
	}
	return 0
}

func (x *GetNodeInfoResponse) GetRunningInstances() int32 {
	if x != nil {
		return x.RunningInstances
	}
	return 0
}

type CreateVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Cpu           int32                  `protobuf:"varint,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        int32                  `protobuf:"varint,4,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMRequest) Reset() {
	*x = CreateVMRequest{}
	mi := &file_nebula_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMRequest) ProtoMessage() {}

func (x *CreateVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMRequest.ProtoReflect.Descriptor instead.
func (*CreateVMRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVMRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateVMRequest) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *CreateVMRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateVMRequest) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *CreateVMRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVMResponse) Reset() {
	*x = CreateVMResponse{}
	mi := &file_nebula_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVMResponse) ProtoMessage() {}

func (x *CreateVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVMResponse.ProtoReflect.Descriptor instead.
func (*CreateVMResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVMResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateVMResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMRequest) Reset() {
	*x = DeleteVMRequest{}
	mi := &file_nebula_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMRequest) ProtoMessage() {}

func (x *DeleteVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMRequest.ProtoReflect.Descriptor instead.
func (*DeleteVMRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteVMRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DeleteVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVMResponse) Reset() {
	*x = DeleteVMResponse{}
	mi := &file_nebula_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVMResponse) ProtoMessage() {}

func (x *DeleteVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVMResponse.ProtoReflect.Descriptor instead.
func (*DeleteVMResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{5}
}

type StartVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMRequest) Reset() {
	*x = StartVMRequest{}
	mi := &file_nebula_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMRequest) ProtoMessage() {}

func (x *StartVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMRequest.ProtoReflect.Descriptor instead.
func (*StartVMRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StartVMRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type StartVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVMResponse) Reset() {
	*x = StartVMResponse{}
	mi := &file_nebula_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVMResponse) ProtoMessage() {}

func (x *StartVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVMResponse.ProtoReflect.Descriptor instead.
func (*StartVMResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StartVMResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartVMResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StopVMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMRequest) Reset() {
	*x = StopVMRequest{}
	mi := &file_nebula_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMRequest) ProtoMessage() {}

func (x *StopVMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMRequest.ProtoReflect.Descriptor instead.
func (*StopVMRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{8}
}

func (x *StopVMRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type StopVMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVMResponse) Reset() {
	*x = StopVMResponse{}
	mi := &file_nebula_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVMResponse) ProtoMessage() {}

func (x *StopVMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVMResponse.ProtoReflect.Descriptor instead.
func (*StopVMResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StopVMResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StopVMResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetVMStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMStatusRequest) Reset() {
	*x = GetVMStatusRequest{}
	mi := &file_nebula_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMStatusRequest) ProtoMessage() {}

func (x *GetVMStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMStatusRequest.ProtoReflect.Descriptor instead.
func (*GetVMStatusRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetVMStatusRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetVMStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Cpu           int32                  `protobuf:"varint,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,4,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        int32                  `protobuf:"varint,5,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVMStatusResponse) Reset() {
	*x = GetVMStatusResponse{}
	mi := &file_nebula_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVMStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVMStatusResponse) ProtoMessage() {}

func (x *GetVMStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVMStatusResponse.ProtoReflect.Descriptor instead.
func (*GetVMStatusResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{11}
}

func (x *GetVMStatusResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetVMStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetVMStatusResponse) GetCpu() int32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *GetVMStatusResponse) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *GetVMStatusResponse) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *GetVMStatusResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	SizeGb        int32                  `protobuf:"varint,2,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiskRequest) Reset() {
	*x = CreateDiskRequest{}
	mi := &file_nebula_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiskRequest) ProtoMessage() {}

func (x *CreateDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiskRequest.ProtoReflect.Descriptor instead.
func (*CreateDiskRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{12}
}

func (x *CreateDiskRequest) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *CreateDiskRequest) GetSizeGb() int32 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

type CreateDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDiskResponse) Reset() {
	*x = CreateDiskResponse{}
	mi := &file_nebula_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDiskResponse) ProtoMessage() {}

func (x *CreateDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDiskResponse.ProtoReflect.Descriptor instead.
func (*CreateDiskResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{13}
}

func (x *CreateDiskResponse) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *CreateDiskResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiskRequest) Reset() {
	*x = DeleteDiskRequest{}
	mi := &file_nebula_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiskRequest) ProtoMessage() {}

func (x *DeleteDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiskRequest.ProtoReflect.Descriptor instead.
func (*DeleteDiskRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteDiskRequest) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

type DeleteDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDiskResponse) Reset() {
	*x = DeleteDiskResponse{}
	mi := &file_nebula_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDiskResponse) ProtoMessage() {}

func (x *DeleteDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDiskResponse.ProtoReflect.Descriptor instead.
func (*DeleteDiskResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{15}
}

type ResizeDiskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DiskId        string                 `protobuf:"bytes,1,opt,name=disk_id,json=diskId,proto3" json:"disk_id,omitempty"`
	NewSizeGb     int32                  `protobuf:"varint,2,opt,name=new_size_gb,json=newSizeGb,proto3" json:"new_size_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeDiskRequest) Reset() {
	*x = ResizeDiskRequest{}
	mi := &file_nebula_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeDiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeDiskRequest) ProtoMessage() {}

func (x *ResizeDiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeDiskRequest.ProtoReflect.Descriptor instead.
func (*ResizeDiskRequest) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ResizeDiskRequest) GetDiskId() string {
	if x != nil {
		return x.DiskId
	}
	return ""
}

func (x *ResizeDiskRequest) GetNewSizeGb() int32 {
	if x != nil {
		return x.NewSizeGb
	}
	return 0
}

type ResizeDiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeDiskResponse) Reset() {
	*x = ResizeDiskResponse{}
	mi := &file_nebula_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeDiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeDiskResponse) ProtoMessage() {}

func (x *ResizeDiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nebula_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeDiskResponse.ProtoReflect.Descriptor instead.
func (*ResizeDiskResponse) Descriptor() ([]byte, []int) {
	return file_nebula_agent_proto_rawDescGZIP(), []int{17}
}

var File_nebula_agent_proto protoreflect.FileDescriptor

const file_nebula_agent_proto_rawDesc = "" +
	"\n" +
	"\x12nebula_agent.proto\x12\x0fnebula.agent.v1\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xca\x01\n" +
	"\x13GetNodeInfoResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12$\n" +
	"\x0ememory_used_mb\x18\x02 \x01(\x03R\fmemoryUsedMb\x12 \n" +
	"\fdisk_used_gb\x18\x03 \x01(\x03R\n" +
	"diskUsedGb\x12!\n" +
	"\fload_average\x18\x04 \x01(\x01R\vloadAverage\x12+\n" +
	"\x11running_instances\x18\x05 \x01(\x05R\x10runningInstances\"\x90\x01\n" +
	"\x0fCreateVMRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\x05R\x03cpu\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x04 \x01(\x05R\x06diskGb\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\"K\n" +
	"\x10CreateVMResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"2\n" +
	"\x0fDeleteVMRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x12\n" +
	"\x10DeleteVMResponse\"1\n" +
	"\x0eStartVMRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"J\n" +
	"\x0fStartVMResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"0\n" +
	"\rStopVMRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"I\n" +
	"\x0eStopVMResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x12GetVMStatusRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xac\x01\n" +
	"\x13GetVMStatusResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\x05R\x03cpu\x12\x1b\n" +
	"\tmemory_mb\x18\x04 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x05 \x01(\x05R\x06diskGb\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\"E\n" +
	"\x11CreateDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12\x17\n" +
	"\asize_gb\x18\x02 \x01(\x05R\x06sizeGb\"A\n" +
	"\x12CreateDiskResponse\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\",\n" +
	"\x11DeleteDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\"\x14\n" +
	"\x12DeleteDiskResponse\"L\n" +
	"\x11ResizeDiskRequest\x12\x17\n" +
	"\adisk_id\x18\x01 \x01(\tR\x06diskId\x12\x1e\n" +
	"\vnew_size_gb\x18\x02 \x01(\x05R\tnewSizeGb\"\x14\n" +
	"\x12ResizeDiskResponse2\x81\x06\n" +
	"\vNebulaAgent\x12X\n" +
	"\vGetNodeInfo\x12#.nebula.agent.v1.GetNodeInfoRequest\x1a$.nebula.agent.v1.GetNodeInfoResponse\x12O\n" +
	"\bCreateVM\x12 .nebula.agent.v1.CreateVMRequest\x1a!.nebula.agent.v1.CreateVMResponse\x12O\n" +
	"\bDeleteVM\x12 .nebula.agent.v1.DeleteVMRequest\x1a!.nebula.agent.v1.DeleteVMResponse\x12L\n" +
	"\aStartVM\x12\x1f.nebula.agent.v1.StartVMRequest\x1a .nebula.agent.v1.StartVMResponse\x12I\n" +
	"\x06StopVM\x12\x1e.nebula.agent.v1.StopVMRequest\x1a\x1f.nebula.agent.v1.StopVMResponse\x12X\n" +
	"\vGetVMStatus\x12#.nebula.agent.v1.GetVMStatusRequest\x1a$.nebula.agent.v1.GetVMStatusResponse\x12U\n" +
	"\n" +
	"CreateDisk\x12\".nebula.agent.v1.CreateDiskRequest\x1a#.nebula.agent.v1.CreateDiskResponse\x12U\n" +
	"\n" +
	"DeleteDisk\x12\".nebula.agent.v1.DeleteDiskRequest\x1a#.nebula.agent.v1.DeleteDiskResponse\x12U\n" +
	"\n" +
	"ResizeDisk\x12\".nebula.agent.v1.ResizeDiskRequest\x1a#.nebula.agent.v1.ResizeDiskResponseB3Z1github.com/milosursulovic/nebula/internal/agentpbb\x06proto3"

var (
	file_nebula_agent_proto_rawDescOnce sync.Once
	file_nebula_agent_proto_rawDescData []byte
)

func file_nebula_agent_proto_rawDescGZIP() []byte {
	file_nebula_agent_proto_rawDescOnce.Do(func() {
		file_nebula_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nebula_agent_proto_rawDesc), len(file_nebula_agent_proto_rawDesc)))
	})
	return file_nebula_agent_proto_rawDescData
}

var file_nebula_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_nebula_agent_proto_goTypes = []any{
	(*GetNodeInfoRequest)(nil),  // 0: nebula.agent.v1.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil), // 1: nebula.agent.v1.GetNodeInfoResponse
	(*CreateVMRequest)(nil),     // 2: nebula.agent.v1.CreateVMRequest
	(*CreateVMResponse)(nil),    // 3: nebula.agent.v1.CreateVMResponse
	(*DeleteVMRequest)(nil),     // 4: nebula.agent.v1.DeleteVMRequest
	(*DeleteVMResponse)(nil),    // 5: nebula.agent.v1.DeleteVMResponse
	(*StartVMRequest)(nil),      // 6: nebula.agent.v1.StartVMRequest
	(*StartVMResponse)(nil),     // 7: nebula.agent.v1.StartVMResponse
	(*StopVMRequest)(nil),       // 8: nebula.agent.v1.StopVMRequest
	(*StopVMResponse)(nil),      // 9: nebula.agent.v1.StopVMResponse
	(*GetVMStatusRequest)(nil),  // 10: nebula.agent.v1.GetVMStatusRequest
	(*GetVMStatusResponse)(nil), // 11: nebula.agent.v1.GetVMStatusResponse
	(*CreateDiskRequest)(nil),   // 12: nebula.agent.v1.CreateDiskRequest
	(*CreateDiskResponse)(nil),  // 13: nebula.agent.v1.CreateDiskResponse
	(*DeleteDiskRequest)(nil),   // 14: nebula.agent.v1.DeleteDiskRequest
	(*DeleteDiskResponse)(nil),  // 15: nebula.agent.v1.DeleteDiskResponse
	(*ResizeDiskRequest)(nil),   // 16: nebula.agent.v1.ResizeDiskRequest
	(*ResizeDiskResponse)(nil),  // 17: nebula.agent.v1.ResizeDiskResponse
}
var file_nebula_agent_proto_depIdxs = []int32{
	0,  // 0: nebula.agent.v1.NebulaAgent.GetNodeInfo:input_type -> nebula.agent.v1.GetNodeInfoRequest
	2,  // 1: nebula.agent.v1.NebulaAgent.CreateVM:input_type -> nebula.agent.v1.CreateVMRequest
	4,  // 2: nebula.agent.v1.NebulaAgent.DeleteVM:input_type -> nebula.agent.v1.DeleteVMRequest
	6,  // 3: nebula.agent.v1.NebulaAgent.StartVM:input_type -> nebula.agent.v1.StartVMRequest
	8,  // 4: nebula.agent.v1.NebulaAgent.StopVM:input_type -> nebula.agent.v1.StopVMRequest
	10, // 5: nebula.agent.v1.NebulaAgent.GetVMStatus:input_type -> nebula.agent.v1.GetVMStatusRequest
	12, // 6: nebula.agent.v1.NebulaAgent.CreateDisk:input_type -> nebula.agent.v1.CreateDiskRequest
	14, // 7: nebula.agent.v1.NebulaAgent.DeleteDisk:input_type -> nebula.agent.v1.DeleteDiskRequest
	16, // 8: nebula.agent.v1.NebulaAgent.ResizeDisk:input_type -> nebula.agent.v1.ResizeDiskRequest
	1,  // 9: nebula.agent.v1.NebulaAgent.GetNodeInfo:output_type -> nebula.agent.v1.GetNodeInfoResponse
	3,  // 10: nebula.agent.v1.NebulaAgent.CreateVM:output_type -> nebula.agent.v1.CreateVMResponse
	5,  // 11: nebula.agent.v1.NebulaAgent.DeleteVM:output_type -> nebula.agent.v1.DeleteVMResponse
	7,  // 12: nebula.agent.v1.NebulaAgent.StartVM:output_type -> nebula.agent.v1.StartVMResponse
	9,  // 13: nebula.agent.v1.NebulaAgent.StopVM:output_type -> nebula.agent.v1.StopVMResponse
	11, // 14: nebula.agent.v1.NebulaAgent.GetVMStatus:output_type -> nebula.agent.v1.GetVMStatusResponse
	13, // 15: nebula.agent.v1.NebulaAgent.CreateDisk:output_type -> nebula.agent.v1.CreateDiskResponse
	15, // 16: nebula.agent.v1.NebulaAgent.DeleteDisk:output_type -> nebula.agent.v1.DeleteDiskResponse
	17, // 17: nebula.agent.v1.NebulaAgent.ResizeDisk:output_type -> nebula.agent.v1.ResizeDiskResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_nebula_agent_proto_init() }
func file_nebula_agent_proto_init() {
	if File_nebula_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nebula_agent_proto_rawDesc), len(file_nebula_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nebula_agent_proto_goTypes,
		DependencyIndexes: file_nebula_agent_proto_depIdxs,
		MessageInfos:      file_nebula_agent_proto_msgTypes,
	}.Build()
	File_nebula_agent_proto = out.File
	file_nebula_agent_proto_goTypes = nil
	file_nebula_agent_proto_depIdxs = nil
}
