// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: nebula_agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NebulaAgent_GetNodeInfo_FullMethodName = "/nebula.agent.v1.NebulaAgent/GetNodeInfo"
	NebulaAgent_CreateVM_FullMethodName    = "/nebula.agent.v1.NebulaAgent/CreateVM"
	NebulaAgent_DeleteVM_FullMethodName    = "/nebula.agent.v1.NebulaAgent/DeleteVM"
	NebulaAgent_StartVM_FullMethodName     = "/nebula.agent.v1.NebulaAgent/StartVM"
	NebulaAgent_StopVM_FullMethodName      = "/nebula.agent.v1.NebulaAgent/StopVM"
	NebulaAgent_GetVMStatus_FullMethodName = "/nebula.agent.v1.NebulaAgent/GetVMStatus"
	NebulaAgent_CreateDisk_FullMethodName  = "/nebula.agent.v1.NebulaAgent/CreateDisk"
	NebulaAgent_DeleteDisk_FullMethodName  = "/nebula.agent.v1.NebulaAgent/DeleteDisk"
	NebulaAgent_ResizeDisk_FullMethodName  = "/nebula.agent.v1.NebulaAgent/ResizeDisk"
)

// NebulaAgentClient is the client API for NebulaAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NebulaAgent is the control-plane -> agent protocol (spec section 28) —
// gRPC replaces the Phase 9 REST version of this same surface.
type NebulaAgentClient interface {
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error)
	StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error)
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error)
	GetVMStatus(ctx context.Context, in *GetVMStatusRequest, opts ...grpc.CallOption) (*GetVMStatusResponse, error)
	CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*CreateDiskResponse, error)
	DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*DeleteDiskResponse, error)
	ResizeDisk(ctx context.Context, in *ResizeDiskRequest, opts ...grpc.CallOption) (*ResizeDiskResponse, error)
}

type nebulaAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNebulaAgentClient(cc grpc.ClientConnInterface) NebulaAgentClient {
	return &nebulaAgentClient{cc}
}

func (c *nebulaAgentClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*DeleteVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVMResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) StartVM(ctx context.Context, in *StartVMRequest, opts ...grpc.CallOption) (*StartVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartVMResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*StopVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopVMResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) GetVMStatus(ctx context.Context, in *GetVMStatusRequest, opts ...grpc.CallOption) (*GetVMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVMStatusResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_GetVMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*CreateDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiskResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_CreateDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*DeleteDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDiskResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_DeleteDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nebulaAgentClient) ResizeDisk(ctx context.Context, in *ResizeDiskRequest, opts ...grpc.CallOption) (*ResizeDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResizeDiskResponse)
	err := c.cc.Invoke(ctx, NebulaAgent_ResizeDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NebulaAgentServer is the server API for NebulaAgent service.
// All implementations must embed UnimplementedNebulaAgentServer
// for forward compatibility.
//
// NebulaAgent is the control-plane -> agent protocol (spec section 28) —
// gRPC replaces the Phase 9 REST version of this same surface.
type NebulaAgentServer interface {
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error)
	StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error)
	StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error)
	GetVMStatus(context.Context, *GetVMStatusRequest) (*GetVMStatusResponse, error)
	CreateDisk(context.Context, *CreateDiskRequest) (*CreateDiskResponse, error)
	DeleteDisk(context.Context, *DeleteDiskRequest) (*DeleteDiskResponse, error)
	ResizeDisk(context.Context, *ResizeDiskRequest) (*ResizeDiskResponse, error)
	mustEmbedUnimplementedNebulaAgentServer()
}

// UnimplementedNebulaAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNebulaAgentServer struct{}

func (UnimplementedNebulaAgentServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedNebulaAgentServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedNebulaAgentServer) DeleteVM(context.Context, *DeleteVMRequest) (*DeleteVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedNebulaAgentServer) StartVM(context.Context, *StartVMRequest) (*StartVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedNebulaAgentServer) StopVM(context.Context, *StopVMRequest) (*StopVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedNebulaAgentServer) GetVMStatus(context.Context, *GetVMStatusRequest) (*GetVMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (UnimplementedNebulaAgentServer) CreateDisk(context.Context, *CreateDiskRequest) (*CreateDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDisk not implemented")
}
func (UnimplementedNebulaAgentServer) DeleteDisk(context.Context, *DeleteDiskRequest) (*DeleteDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDisk not implemented")
}
func (UnimplementedNebulaAgentServer) ResizeDisk(context.Context, *ResizeDiskRequest) (*ResizeDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeDisk not implemented")
}
func (UnimplementedNebulaAgentServer) mustEmbedUnimplementedNebulaAgentServer() {}
func (UnimplementedNebulaAgentServer) testEmbeddedByValue()                     {}

// UnsafeNebulaAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NebulaAgentServer will
// result in compilation errors.
type UnsafeNebulaAgentServer interface {
	mustEmbedUnimplementedNebulaAgentServer()
}

func RegisterNebulaAgentServer(s grpc.ServiceRegistrar, srv NebulaAgentServer) {
	// If the following call panics, it indicates UnimplementedNebulaAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NebulaAgent_ServiceDesc, srv)
}

func _NebulaAgent_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).StartVM(ctx, req.(*StartVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVMStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_GetVMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).GetVMStatus(ctx, req.(*GetVMStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_CreateDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).CreateDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_CreateDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).CreateDisk(ctx, req.(*CreateDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_DeleteDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).DeleteDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_DeleteDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).DeleteDisk(ctx, req.(*DeleteDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NebulaAgent_ResizeDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NebulaAgentServer).ResizeDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NebulaAgent_ResizeDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NebulaAgentServer).ResizeDisk(ctx, req.(*ResizeDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NebulaAgent_ServiceDesc is the grpc.ServiceDesc for NebulaAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NebulaAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nebula.agent.v1.NebulaAgent",
	HandlerType: (*NebulaAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNodeInfo",
			Handler:    _NebulaAgent_GetNodeInfo_Handler,
		},
		{
			MethodName: "CreateVM",
			Handler:    _NebulaAgent_CreateVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _NebulaAgent_DeleteVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _NebulaAgent_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _NebulaAgent_StopVM_Handler,
		},
		{
			MethodName: "GetVMStatus",
			Handler:    _NebulaAgent_GetVMStatus_Handler,
		},
		{
			MethodName: "CreateDisk",
			Handler:    _NebulaAgent_CreateDisk_Handler,
		},
		{
			MethodName: "DeleteDisk",
			Handler:    _NebulaAgent_DeleteDisk_Handler,
		},
		{
			MethodName: "ResizeDisk",
			Handler:    _NebulaAgent_ResizeDisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nebula_agent.proto",
}
